# Generated by Django 3.0.5 on 2022-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, default='GLYDMlMN', max_length=8, null=True, unique=True),
        ),
    ]
