# Generated by Django 3.0.5 on 2022-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, default='2N4EDenP', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(default='LEK1qCA7bN', max_length=100),
        ),
    ]
