# Generated by Django 3.0.5 on 2022-05-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_auto_20220510_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, default='5GQ2RBAi', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(default='RGDeMB3PTN', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
